"""Users

Revision ID: 03f57e38c258
Revises: 18213329b38e
Create Date: 2023-05-06 20:48:05.800600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f57e38c258'
down_revision = '18213329b38e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'password')
    op.add_column('news', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news', 'author', ['author_id'], ['id'])
    op.drop_column('news', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'author_id')
    op.add_column('author', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
