"""Users

Revision ID: 18213329b38e
Revises: c35ec289fc27
Create Date: 2023-05-06 20:20:39.165516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18213329b38e'
down_revision = 'c35ec289fc27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('author', sa.Column('email', sa.String(), nullable=True))
    op.add_column('author', sa.Column('password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'author', ['email'])
    op.drop_column('author', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_column('author', 'password')
    op.drop_column('author', 'email')
    op.drop_column('author', 'picture')
    # ### end Alembic commands ###
